// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxKUV6nMkDI7u911KJd4X0clmgxibPTo',
    appId: '1:250485548926:web:712dc974cacbe4db70b52f',
    messagingSenderId: '250485548926',
    projectId: 'notes-b4e3e',
    authDomain: 'notes-b4e3e.firebaseapp.com',
    storageBucket: 'notes-b4e3e.firebasestorage.app',
    measurementId: 'G-1HL3Q015KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5tjiOTuQk6Vfv-gsRLloY3RDEYPGObLY',
    appId: '1:250485548926:android:507aef2dd78fbda370b52f',
    messagingSenderId: '250485548926',
    projectId: 'notes-b4e3e',
    storageBucket: 'notes-b4e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2_8AWrU_IyQCfU9m718OVIrCT1XwW10',
    appId: '1:250485548926:ios:a4d2ea24bf45899170b52f',
    messagingSenderId: '250485548926',
    projectId: 'notes-b4e3e',
    storageBucket: 'notes-b4e3e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU2_8AWrU_IyQCfU9m718OVIrCT1XwW10',
    appId: '1:250485548926:ios:a4d2ea24bf45899170b52f',
    messagingSenderId: '250485548926',
    projectId: 'notes-b4e3e',
    storageBucket: 'notes-b4e3e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxKUV6nMkDI7u911KJd4X0clmgxibPTo',
    appId: '1:250485548926:web:e37da0c343dbd3d370b52f',
    messagingSenderId: '250485548926',
    projectId: 'notes-b4e3e',
    authDomain: 'notes-b4e3e.firebaseapp.com',
    storageBucket: 'notes-b4e3e.firebasestorage.app',
    measurementId: 'G-2ECHEXR81M',
  );
}
